apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ewgkbnqz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ewgkbnqz:f88bacaf837ed7ee0df5c099eb696f6ebecaa610@sha256:e61b0521b4d77a7947d00ad8600a393c10f87cd28ae251ce1413678158ecd588
          name: container-image
